### ISSUE TITLE
Codable decode integers into floats

### ISSUE THREAD

**Issue by molikto** [fumoboy007/msgpack-swift#1]
If the original msgpack is encoded in JavaScript, and then decode using Codable, the it's good a integer is decoded as float

**Comment by fumoboy007** [comment]
Ah, I forgot about JavaScript where numbers are all floating point. Will do, thanks!

**Comment by fumoboy007** [comment]
Oops, I misunderstood. We should allow decoding an integer value as a floating point type, not the other way around.
